version: '3'
services:
  bucky-core:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bucky-core
    volumes:
      - .:/bucky-core
      - .sample:/app
    tty: true
  chrome:
    image: seleniarm/standalone-chromium:latest
    container_name: chrome
    ports:
      - '4444:4444'
      - '5901:5900'
    shm_size: 1G